"""initial connectors schema

Revision ID: f5b2bc2745d7
Revises: 
Create Date: 2026-05-20 15:53:22.116551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'f5b2bc2745d7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connectors',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('connector_type', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('credentials', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('webhook_secret', sa.String(), nullable=True),
    sa.Column('sync_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_connectors_connector_type', 'connectors', ['connector_type'], unique=False)
    op.create_index('ix_connectors_is_active', 'connectors', ['is_active'], unique=False)
    op.create_index('ix_connectors_tenant_id', 'connectors', ['tenant_id'], unique=False)
    op.create_table('connector_runs',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('connector_id', sa.UUID(), nullable=False),
    sa.Column('run_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('items_processed', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['connectors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_connector_runs_connector_id', 'connector_runs', ['connector_id'], unique=False)
    op.create_index('ix_connector_runs_status', 'connector_runs', ['status'], unique=False)
    op.create_index('ix_connector_runs_tenant_id', 'connector_runs', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_connector_runs_tenant_id', table_name='connector_runs')
    op.drop_index('ix_connector_runs_status', table_name='connector_runs')
    op.drop_index('ix_connector_runs_connector_id', table_name='connector_runs')
    op.drop_table('connector_runs')
    op.drop_index('ix_connectors_tenant_id', table_name='connectors')
    op.drop_index('ix_connectors_is_active', table_name='connectors')
    op.drop_index('ix_connectors_connector_type', table_name='connectors')
    op.drop_table('connectors')
    # ### end Alembic commands ###
