"""initial retrieval schema

Revision ID: 0e3d2e95964c
Revises: 6a470f917f62
Create Date: 2026-05-16 06:25:07.782568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0e3d2e95964c'
down_revision: Union[str, None] = '6a470f917f62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
