"""initial retrieval schema

Revision ID: 6a470f917f62
Revises: 
Create Date: 2026-05-16 05:39:16.391039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '6a470f917f62'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retrieval_logs',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('source_filter', sa.String(length=50), nullable=True),
    sa.Column('chunks_retrieved', sa.Integer(), nullable=False),
    sa.Column('chunks_after_rerank', sa.Integer(), nullable=False),
    sa.Column('grounding_passed', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_retrieval_logs_tenant_created', 'retrieval_logs', ['tenant_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_retrieval_logs_tenant_id'), 'retrieval_logs', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_retrieval_logs_tenant_id'), table_name='retrieval_logs')
    op.drop_index('ix_retrieval_logs_tenant_created', table_name='retrieval_logs')
    op.drop_table('retrieval_logs')
    # ### end Alembic commands ###
